title="Configuration file"

max_cands=20

[attributes]
[attributes.COMPANY]
コーポレートスローガン="Free"
ふりがな="Free"
主要株主="Free"
事業内容="Data"
代表者="Free"
別名="Free"
創業国="Geo"
創業地="Geo"
創業時の事業="Data"
創業者="Free"
取扱商品="Data"
商品名="Free"
売上高データの年="Date"
売上高_単体="Number"
売上高_連結="Number"
売上高_連結データの年="Date"
子会社_合弁会社="Free"
従業員数_単体="Number"
従業員数_単体データの年="Date"
従業員数_連結="Number"
従業員数_連結データの年="Date"
本拠地="Geo"
本拠地国="Geo"
業界="Data"
業界内地位_規模="Data"
正式名称="Free"
社名使用開始年="Date"
種類="Data"
解散年="Date"
設立年="Date"
買収_合併した会社="Free"
資本金="Number"
資本金データの年="Date"
起源="Free"
過去の社名="Free"

[attributes.AIRPORT]
IATA_空港コード="Free"
ICAO_空港コード="Free"
ふりがな="Free"
別名="Free"
名前の謂れ="Free"
名称由来人物の地位職業名="Free"
国="Geo"
年間利用客数="Number"
年間利用者数データの年="Date"
年間発着回数="Number"
年間発着回数データの年="Date"
# # 座標・経度=x
# # 座標・緯度=x
所在地="Geo"
旧称="Free"
標高="Number"
母都市="Geo"
滑走路の長さ="Number"
滑走路数="Number"
総面積="Number"
近隣空港="Free"
運営者="Free"
# # 運用時間=x
開港年="Date"

[attributes.PERSON]
ふりがな="Free"
両親="Free"
作品="Free"
別名="Free"
参加イベント="Data"
受賞歴="Data"
国籍="Geo"
学歴="Data"
家族="Free"
居住地="Geo"
師匠="Free"
所属組織="Data"
# 時代=x
本名="Free"
死因="Data"
没地="Geo"
没年月日="Date"
生年月日="Date"
生誕地="Geo"
異表記="Free"
# 称号=x
職業="Data"

[attributes.CITY]
ふりがな="Free"
人口="Number"
人口データの年="Date"
人口密度="Number"
別名="Free"
友好市区町村="Geo"
合併市区町村="Geo"
国="Geo"
# 国内位置=x
地名の謂れ="Free"
# 地形=x
# 座標・経度=x
# 座標・緯度=x
# 恒例行事=x
成立年="Date"
所在地="Geo"
施設="Data"
旧称="Free"
温泉_鉱泉="Free"
特産品="Data"
# 産業=x
種類="Data"
# 観光地=x
鉄道会社="Free"
面積="Number"
首長="Free"

[attributes.COMPOUND]
CAS_番号="Free"
別称="Free"
化学式="Free"
原材料="Data"
商標名="Free"
密度="Number"
沸点="Number"
特性="Data"
生成化合物="Data"
用途="Data"
示性式="Free"
種類="Data"
融点="Number"
製造方法="Free"
読み="Free"
