title = "Data for Geo Refiner"

countries = """
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?s ?l WHERE {
  ?s rdf:type schema:Country .
  ?s rdfs:label ?l ;
  FILTER(LANG(?l) = 'ja') . 
  FILTER NOT EXISTS {
    ?s schema:dissolutionDate ?d 
  }
} limit 5
"""